apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: test-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template: 
    metadata: 
      name: opod
      labels:
        app: test
    spec:
      containers:
      - name: testcon
        image: nginx

