apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-1
spec:
  selector:
    matchLabels:
      app: sleep-1
  template:
    metadata:
      labels:
        app: sleep-1
    spec:
      containers:
        - name: sleep-1
          image: docker.io/library/sleepy:1.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
